metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  processors:
    - add_docker_metadata: ~

- module: elasticsearch
  metricsets: ["node", "cluster_stats"]
  hosts: ["http://elasticsearch:9200"]
  period: 10s

- module: kibana
  metricsets: ["status"]
  hosts: ["http://kibana:5601"]
  period: 10s

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.template:
  name: "metricbeat"
  pattern: "metricbeat-*"
  overwrite: true

logging.level: info